name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'CMakeLists.txt'
      - 'src/'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          sudo apt update
          sudo apt install llvm-12
      - name: Build
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D SANITIZERS=ON -D LLVM_DIR=/usr/lib/llvm-12/cmake
          cmake --build build -j2
      - name: Run
        run: |
          ./build/Analyzer ./sample-programs/class-hierarchy
